### ISSUE TITLE
Add WOFF2 format

### ISSUE THREAD

**Issue by sergejmueller** [primer/octicons#3]
Chrome 36 will support the next generation WOFF 2.0 web font format.

File: [octicons.woff2](https://db.tt/k2dkrJ4w)
Converted via https://gist.github.com/sergejmueller/cf6b4f2133bcb3e2f64a

CSS changes:
```css
@font-face {
  font-family: 'octicons';
  src: url('octicons.eot?#iefix') format('embedded-opentype'),
       url('octicons.woff2') format('woff2'),
       url('octicons.woff') format('woff'),
       url('octicons.ttf') format('truetype'),
       url('octicons.svg#octicons') format('svg');
  font-weight: normal;
  font-style: normal;
}
```
